config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'top#index'
  get 'posts' => 'posts#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :name, :title, presence: true
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :title, :picture)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= form_for(@picture) do |f| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

        <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :名前 %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :タイトル %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :写真 %><br>
      <%= f.file_field :picture, class: 'form-control' %>
      <%= f.hidden_field :picture_cache %>
    </div>
    <div class="actions">
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>

app/views/pictures/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

<%= link_to '戻る', pictures_path %>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-6 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>投稿一覧</h1>
      <%= link_to '新規投稿', new_picture_path, class: 'btn btn-default' %>

    <% @pictures.each do |picture| %>
    <div class="row">
      <p>名前:<%= picture.name %></p>
      <p>タイトル:<%= picture.title %></p>
      <p>写真:<%= image_tag picture.picture %></p>
      <%= link_to "編集", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to '削除', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %>
      <% end %>
    </div>

<br>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

<%= link_to '戻る', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @picture.picture.url %>
</p>

<%= link_to '編集', edit_picture_path(@picture) %> |
<%= link_to '戻る', pictures_path %>